### ISSUE TITLE
[Bug] Certain plug-ins show up in the update logs even when we are using the latest(same) version.

### ISSUE THREAD

**Issue by PhoenixCodingStuff** [TheSilentPro/Informant#2]
Example - Slimebot , Quests
![Screenshot_2022-05-04-11-54-19-825_com discord](https://user-images.githubusercontent.com/97077949/166631908-7c152709-c6f3-4f8e-87d3-528e8f8f5257.jpg)

**Comment by TheSilentPro** [comment]
Version string has to match exactly. As you can see they don't. 
Also you can use discord for support faster github is dumb and doesn't notify me.

**Comment by PhoenixCodingStuff** [comment]
Nah I have just downloaded the one from spigot (after it came) , it gave me that one , thank you for clarifying the version thing though
